version: '3.8'

services:
  accountbank-api-spring:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082

      SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED: "false"

      SPRING_DATASOURCE_URL: jdbc:mariadb://accountbank-api-mariadb:3307/accountbankapi
      SPRING_DATASOURCE_USERNAME: accountbankuser
      SPRING_DATASOURCE_PASSWORD: accountbankpassword

      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
    depends_on:
      - accountbank-api-mariadb

  accountbank-api-mariadb:
    image: mariadb:latest
    container_name: mariadb-accountbankapi
    restart: always
    command: --port=3307
    environment:
      MYSQL_DATABASE: accountbankapi
      MYSQL_USER: accountbankuser
      MYSQL_PASSWORD: accountbankpassword
      MYSQL_ROOT_PASSWORD: accountbankrootpassword
    ports:
      # hote:conteneur_interne
      - "3382:3307"
    volumes:
      - mariadb_data_bank:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql

  operation-api-spring:
    build:
      context: ../../OperationAPI
      dockerfile: docker/Dockerfile
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:mariadb://operation-api-mariadb:3308/operationapi
      SPRING_DATASOURCE_USERNAME: operationuser
      SPRING_DATASOURCE_PASSWORD: operationpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
    depends_on:
      - operation-api-mariadb

  operation-api-mariadb:
    image: mariadb:latest
    container_name: mariadb-operationapi
    restart: always
    command: --port=3308
    environment:
      MYSQL_DATABASE: operationapi
      MYSQL_USER: operationuser
      MYSQL_PASSWORD: operationpassword
      MYSQL_ROOT_PASSWORD: operationrootpassword
    ports:
      - "3383:3308"
    volumes:
      - mariadb_data_operation:/var/lib/mysql
      - ../../OperationAPI/docker/data.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb_data_bank:
  mariadb_data_operation:
